# 生产环境配置
spring:
  # 生产环境数据源配置
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/quick_code?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8}
    username: ${DB_USERNAME:quick_code}
    password: ${DB_PASSWORD:your_secure_password}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000

  # 生产环境JPA配置 - 安全的迁移策略
  jpa:
    hibernate:
      # 生产环境使用validate模式，确保数据库结构与实体匹配
      # 如需更新数据库结构，应使用专门的迁移脚本
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false
        use_sql_comments: false
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
        # 生产环境启用二级缓存
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: org.hibernate.cache.jcache.JCacheRegionFactory

  # 生产环境Redis配置
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: ${REDIS_DATABASE:0}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 2
          max-wait: 2000ms

# 生产环境日志配置
logging:
  level:
    com.quickcode: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
  file:
    name: /var/log/quick-code/application.log
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 30
      total-size-cap: 3GB

# 生产环境安全配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
  security:
    enabled: true

# 生产环境应用配置
app:
  jwt:
    secret: ${JWT_SECRET:your_very_secure_jwt_secret_key_here}
    access-token-expiration: 86400000  # 24小时
    refresh-token-expiration: 604800000 # 7天
  
  file:
    upload-dir: ${UPLOAD_DIR:/var/quickcode/uploads}
    max-file-size: 50MB
    max-request-size: 100MB
  
  cors:
    allowed-origins: ${CORS_ORIGINS:https://quickcode.com,https://www.quickcode.com}
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
    allow-credentials: true
