# 开发环境配置
spring:
  # 开发环境数据源配置
  datasource:
    url: jdbc:mysql://mysql:3306/quick_code?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: quick_code_user
    password: quick_code_pass
  
  # 开发环境JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  
  # 开发环境Redis配置
  data:
    redis:
      host: redis
      port: 6379
      password: redis_pass
      database: 0
  
  # 开发工具配置
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
    livereload:
      enabled: true

# 开发环境日志配置
logging:
  level:
    com.quickcode: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.data.redis: DEBUG

# 开发环境应用配置
app:
  jwt:
    secret: dev-jwt-secret-key-change-in-production
  
  minio:
    endpoint: http://minio:9000
    access-key: minioadmin
    secret-key: minioadmin123
    bucket: quick-code-files

# 开发环境监控配置
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
