# 开发环境配置
spring:
  # 开发环境数据源配置
  datasource:
    url: jdbc:mysql://192.168.31.89:3306/quick_code?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: qt-data
    password: BYDXHXYdcnkJdBma

  # 开发环境JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  # 开发环境Redis配置
  data:
    redis:
      host: 192.168.31.89
      port: 6379
      password: PDaceKR58Cw6McFj
      database: 0

  # 开发工具配置
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
    livereload:
      enabled: true

# 开发环境日志配置 - 详细配置见logback-spring.xml
# 这里只保留必要的环境变量配置

# 开发环境应用配置
app:
  jwt:
    secret: dev-jwt-secret-key-change-in-production

  minio:
    endpoint: http://minio:9000
    access-key: minioadmin
    secret-key: minioadmin123
    bucket: quick-code-files

# 开发环境监控配置
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
